export * from './contacto.repository';
export * from './historia-clinica.repository';
export * from './mascota.repository';
export * from './pedido.repository';
export * from './permisos.repository';
export * from './plan.repository';
export * from './rol.repository';
export * from './sucursal.repository';
export * from './usuario.repository';
